#!/bin/bash

#PREFIX="../data/MA1_Neilan_deg"
#PREFIX="../data/MA1_NeilanCG_deg"
#PREFIX="../data/MA1_NeilanCG_GradJump_deg"
#PREFIX="../data/MA2_NeilanCG_GradJump_deg"
PREFIX="../data/MA3_NeilanCG_deg"

#OUTPUT1="MA1_Neilan_h1" OFFSET1=23 OFFSET2=24
#OUTPUT1="MA1_NeilanCG_h1" OFFSET1=25 OFFSET2=26
#OUTPUT1="MA1_NeilanCG_GradJump_h1" OFFSET1=34 OFFSET2=35
#OUTPUT1="MA2_NeilanCG_GradJump_l2" OFFSET1=34 OFFSET2=35
OUTPUT1="MA3_NeilanCG_h1" OFFSET1=25 OFFSET2=26


gnuplot << EOF

#set axis data
set logscale y 
#set yrange [1e-10:1]
set format y "%.0e"
set ytics 1e-10,1e-1

set grid ytics

set xtics ("1/2" 1, "1/4" 2, "1/8" 3, "1/16" 4, "1/32" 5, "1/64" 6, "1/128" 7, "1/256" 8)

set style line 1 lc rgb 'skyblue' pt 5   # square
set style line 2 lc rgb 'orange-red' pt 7   #circle
#set style line 3 lc rgb '#FF4500' pt 9   #triangle
set style line 3 lc rgb 'grey' pt 5   # square
set style line 4 lc rgb 'blue' pt 7   #circle
set style line 5 lc rgb 'red' pt 9   #triangle
set style line 6 lc rgb 'black' pt 5   # square
set style line 6 lc rgb 'black' pt 5   # square
set style line 8 lc rgb 'navy' pt 7   #circle
set style line 9 lc rgb 'dark-red' pt 9   #triangle

#plot
LIST = system("ls -1 $PREFIX*h1errornorm")
FILES = words(LIST)
FILE(i) = word(LIST,i)

plot for [i=1:FILES] FILE(i) every 1::2  notitle with lines ls i, for [i=1:FILES] FILE(i) every 1::2  title 'deg '.FILE(i)[$OFFSET1:$OFFSET1].' '.FILE(i)[$OFFSET2:$OFFSET2] ls i

set terminal postscript color
set output '$OUTPUT1.ps'
replot
q
EOF

ps2pdf $OUTPUT1.ps $OUTPUT1.pdf
