#!/bin/bash

PREFIXES="../data21-10/MA1_Neilan_GradJump_deg ../data21-10/MA2_Neilan_GradJump_deg ../data21-10/MA3_Neilan_GradJump_deg ../data21-10/MA4_Neilan_GradJump_deg"
#PREFIXES="../data/MA1_Brenner_deg ../data/MA2_Brenner_deg ../data/MA3_Brenner_deg ../data/MA4_Brenner_deg"

#OUTPUT=(MA1_Neilan_ MA2_Neilan_ MA3_Neilan_ MA4_Neilan_)
OUTPUT=(MA1_Neilan_GradJump21-10 MA2_Neilan_GradJump21-10 MA3_Neilan_GradJump21-10 MA4_Neilan_GradJump21-10)
OFFSET1=32
OFFSET2=33

#   OUTPUT1="MA1_Neilan_h1" OFFSET1=23 OFFSET2=24
#   OUTPUT1="MA2_Neilan_h1" OFFSET1=23 OFFSET2=24
#    OUTPUT1="MA3_Neilan_h1" OFFSET1=23 OFFSET2=24
# OUTPUT1="MA4_Neilan_l2" OFFSET1=23 OFFSET2=24
   OUTPUT1="test_MA1_Neilan_GradJump_h1" OFFSET1=32 OFFSET2=33
#     OUTPUT1="MA2_Neilan_GradJump_l2" OFFSET1=32 OFFSET2=33
#   OUTPUT1="MA3_Neilan_GradJump_l2" OFFSET1=32 OFFSET2=33
#  OUTPUT1="MA4_Neilan_GradJump_h1" OFFSET1=32 OFFSET2=33
#OUTPUT1="MA1_ourMethod" OFFSET1=16 OFFSET2=18
#   OUTPUT1="MA1_iteratedNeilan_l2" OFFSET1=40 OFFSET2=41
#    OUTPUT1="MA1_iterated_Neilan_l2" OFFSET1=32 OFFSET2=41
#  OUTPUT1="simpleMA2_iteratedNeilan_l2" OFFSET1=40 OFFSET2=41
#OUTPUT1="MAConst_Neilan_GradJump_l2" OFFSET1=39 OFFSET2=41

i=0

for NORM in "l2" "h1"
do

  echo $NORM

  for PREFIX in $PREFIXES
  do

  echo $PREFIX

  ls -1 ${PREFIX}*${NORM}errornorm
gnuplot << EOF

		#set axis data
		set logscale y 
		#set yrange [1e-10:1]
		set format y "%.0e"
		#set ytics 1e-10,1e-1
		set xlabel 'h'
		set ylabel 'H1 error'

		set size ratio 0.95

		set key outside right

		 set xtics ("init" 0, "1/2" 1, "1/4" 2, "1/8" 3, "1/16" 4, "1/32" 5, "1/64" 6, "1/128" 7)
		#  set xtics ("1/2" 0, "1/4" 15, "1/8" 30, "1/16" 45, "1/32" 60, "1/64" 75, "1/128" 90, "1/256" 105)

		set style line 1 lc rgb 'skyblue' pt 5   # square
		set style line 2 lc rgb 'orange-red' pt 7   #circle
		#set style line 3 lc rgb '#FF4500' pt 9   #triangle
		set style line 3 lc rgb 'grey' pt 5   # square
		set style line 4 lc rgb 'blue' pt 7   #circle
		set style line 5 lc rgb 'red' pt 9   #triangle
		set style line 6 lc rgb 'black' pt 5   # square
		set style line 7 lc rgb 'green' pt 5   # square
		set style line 8 lc rgb 'dark-red' pt 7   #circle
		set style line 9 lc rgb 'dark-red' pt 9   #triangle

		#plot
		LIST = system("ls -1 ${PREFIX}*${NORM}errornorm")
		FILES = words(LIST)
		FILE(i) = word(LIST,i)

		 plot for [i=1:FILES] FILE(i) every 1::1 title 'deg '.FILE(i)[$OFFSET1:$OFFSET1].' '.FILE(i)[$OFFSET2:$OFFSET2] with lp ls i
		#  plot for [i=1:FILES] FILE(i) every 1::1 title 'deg '.FILE(i)[$OFFSET1:$OFFSET1] with lp ls i

		set terminal postscript color
		set output '${OUTPUT[i]}$NORM.ps'
		replot
		q
EOF

	echo $OUTPUT
	echo ${OUTPUT[2]} $i
	echo "output written to ${OUTPUT[i]}${NORM}"

	ps2pdf ${OUTPUT[i]}${NORM}.ps ${OUTPUT[i]}${NORM}.pdf
	
	i=$((i+1))
	done
done
